version: '3.1'
services:
  db:
    image: mysql
    container_name: springboot2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - springboot_data:/var/lib/mysql

volumes:
  springboot_data: